blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions & Discussions
    url: https://github.com/shehab-go/smart-financial-tracker/discussions
    about: Please ask questions here instead of opening a bug report.
