complexity:
  TooManyFunctions:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 60
  LargeClass:
    active: true
    threshold: 600

style:
  MaxLineLength:
    active: true
    maxLineLength: 140
  WildcardImport:
    active: true
    excludeImports:
      - 'kotlinx.android.synthetic.*'

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*' # Relaxed for Compose

potential-bugs:
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignored|expected|serialVersionUID)'
